### ISSUE TITLE
Use/enforce `cargo fmt`

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#131]
This repo has no code style guide (at least at the formatting level).

We should use `rustfmt` (as per the engineering guidelines) and enforce it by running `cargo fmt --all -- --check` in CI (so all code that is merged must have been formatted).

This will remove the need to think about formatting and also allow editor integrations to be used to format code as you type etc.

**Comment by Atul9** [comment]
@janslow I would like to take this up. I would like to start by first running `cargo fmt` on the codebase and then adding config to run `cargo fmt --all -- --check` on CI.

**Comment by clux** [comment]
This will screw up git history if we do it in one go. We should do this at some point when doing big changes to individual folders. Closing this for now. Sorry @Atul9.
