### ISSUE TITLE
initContainers to read secrets

### ISSUE THREAD

**Issue by clux** [Babylonpartners/shipcat#167]
Currently they do not support it.

- [ ] extend [InitContainer](https://github.com/Babylonpartners/shipcat/blob/master/shipcat_definitions/src/structs/initcontainer.rs) to take a `pub env: EnvVars`
- [ ] extend [evar secret fetching](https://github.com/Babylonpartners/shipcat/blob/e3127ba4670f3d409966e679093a547a768f3421/shipcat_definitions/src/manifest.rs#L913) to cover `initContainers`
- [ ] extend example chart to [not just inline initContainers](https://github.com/Babylonpartners/shipcat/blob/e3127ba4670f3d409966e679093a547a768f3421/examples/charts/base/templates/deployment.yaml#L149-L151)

Needs testing with minikube using the chart therein, tests folder before making a new version.

**Comment by janslow** [comment]
I'm doing some changes which should support that at the moment (making init containers, sidecars, workers, jobs and cronjobs more similar)

**Comment by clux** [comment]
Ah, that's great. @rupert might also be happy to hear that since I showed this to him :-)

**Comment by janslow** [comment]
Fixed by #168
