### ISSUE TITLE
Overriding cronJobs with an empty array doesn't work

### ISSUE THREAD

**Issue by florent-babylon** [Babylonpartners/shipcat#19]
See https://github.com/Babylonpartners/manifests/pull/3316

Overriding the `cronJobs` key in a region with an empty array doesn't work:
```yaml
cronJobs: []
```

Expected result
===

No cronJobs are being scheduled for that environment

Actual result
===

All cronJobs from the base shipcat.yaml are picked up, and the override is ignored.

**Comment by clux** [comment]
I believe this is fixed now @janslow ?

**Comment by janslow** [comment]
Yep
