### ISSUE TITLE
Make Shipcat apply and CRD reconcile an atomic operation

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#191]
Currently, `shipcat cluster crd reconcile` is run first, then each service's Helm release is upgrade, if necessary.

This means, if the release upgrade fails, the CRD has already been updated, so Shipcat will think the service is up to date. Therefore it won't try to upgrade the release again on the next run, unless it's manually forced to do so.

Updating the CRD should be done atomically with the Helm upgrade (or at the very least, after the upgrade), to prevent this occurring.

**Comment by clux** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

```rust
pub struct ShipcatManifestStatus {
    pub conditions: Option<Vec<ManifestCondition>>,
    /// git version deployed from
    pub revision: String,
    // kong status?
    // canary status?
}

pub struct ManifestCondition {
    pub last_update_time: Option<Time>,
    pub message: String,
    pub reason: String,
    pub status: String,
    #[serde(rename = "type")
    pub type_: UpgradeState,
}

pub enum UpgradeState {
    // Complete, diff in reason, time taken to upgrade
    COMPLETE,
    // CRD applied with diff, diff in reason?
    STARTED,
    // main deployment failed to rollout in time (snapshot state in reason)
    TIMEOUT,
    // vault issues, chart issues, other uncaught issues (error in reason)
    ERROR,
}
```

**Comment by janslow** [comment]
The status could also be useful for monitoring dashboards, which could tell if there is an error during deployments.

**Comment by clux** [comment]
Have started fleshing out the .status object now. Was wondering how generic it was within kube so did a bunch of digging. The interested can read [this thread](https://github.com/clux/kube-rs/issues/43) on kube-rs.

A pr will appear here shortly regardless.

**Comment by clux** [comment]
By the way the original bug has a workaround at the moment:

- `shipcat cluster crd reconcile` (fast reconcile, prone to problem)
- `SHIPCAT_MASS_RECONCILE=1 shipcat cluster crd reconcile` (slower, not prone to problem)

Can run the latter less frequently for now, but this is all going to get cleaned up once the `.status` objects are observeable.
