### ISSUE TITLE
Shipcat checking Vault for templated secrets

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#192]
Shipcat reconcile sometimes fail because it's trying to fetch that a templated  secret from Vault.

```
18:22:07 shipcat: cluster error: secret 'secret/region/core-auth-2/CLIENT_ID'
18:22:07 shipcat: caused by: could not access URL 'https://vault-uk.preprod.babylontech.co.uk/v1/secret/preprod-uk/core-auth-2/CLIENT_ID'
18:22:07 shipcat: caused by: unexpected HTTP status: 404 Not Found
```

https://github.com/Babylonpartners/manifests/blob/master/services/core-auth-2/shipcat.yml#L73

```yaml
# shipcat.yml
env:
  CLIENT_ID: "{{ kong.consumers['core-auth-2'].oauth_client_id }}"
```

Therefore, the Vault secret is actually `secret/preprod-uk/kong/consumers/core-auth-2_oauth_client_id`

This has happened with multiple services.

**Comment by clux** [comment]
This was fixed in crd reconcile last version.
