### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by clux** [Babylonpartners/shipcat#253]
I wanted to do some dumb vectorised thing like this:

![shipcat](https://user-images.githubusercontent.com/134092/62698042-118a6a80-b9d4-11e9-811c-41af41d07718.png)

but don't know how to illustrator.

**Comment by ngodec** [comment]
I can do it :D

**Comment by ngodec** [comment]
I assume it's a cat with a steering wheel? What colours do you envisage?

**Comment by clux** [comment]
That's a cat behind the ship's helm. Normally the wheel is wooden, but only planned on having the cat loom somewhat ominously in the background; controlling the world in the way cats normally do.

Hadn't really thought too much about the colour of the cat. Some dark blue/green lines perhaps? Needs to have a white BG.

**Comment by clux** [comment]
Result is https://github.com/Babylonpartners/shipcat/blob/master/logo/shipcat_logo_600px.png now.

Impressive outcome since my original drawing has been described as a "satan beetle".
