### ISSUE TITLE
Feature request - Shipcat should warn if not running latest version 

### ISSUE THREAD

**Issue by alexmorley** [Babylonpartners/shipcat#313]
Currently the vast majority of errors on shipcat are due to users not having the latest version. We could reduce support requests by throwing a warning if this is the case.

Thoughts?

**Comment by hpapadopoulos** [comment]
I think this is similar:
https://github.com/Babylonpartners/shipcat/issues/263

**Comment by alexmorley** [comment]
yup. Closing.
