### ISSUE TITLE
Add a smarter difference system

### ISSUE THREAD

**Issue by clux** [Babylonpartners/shipcat#56]
[derive-diff](https://github.com/polachok/derive-diff/blob/master/test-derive-diff/src/lib.rs) or [difference](https://github.com/johannhof/difference.rs) crates can let us spot the exact changes we are making either when:

- we get an updated crd in raftcat
- `shipcat diff service` which can diff against the CRD

This allows us to have a working diff withouth needing kube 1.13. Plus it can be used to check what you change for pre-merge checks in manifests.

**Comment by janslow** [comment]
It'd be useful if this could work without requiring any K8s/Vault access, so that refactoring changes (which might make major changes to the manifests, but shouldn't to the resulting CRD for a region), can be checked by any engineer.

(it'd could also be consumed by the CRP check in CircleCI, rather than just checking when the `prod-uk.yml` file was touched)

**Comment by clux** [comment]
I can do the simple file_vs_git_master algorithm first since kubectl diff is still lacking.

What I'm thinking is comparing internal `shipcat values <svc>` with `shipcat values <svc>` after switching back to master and stashing local changes:

```
lhs=shipcat values svc
git checkout master
warn if master is out of date
git stash
rhs=shipcat values svc
git stash pop
git checkout -
```

does that seem sensible?

**Comment by clux** [comment]
Tried two other algorithms while working on this. The first one is awful. Leaving it in here:

```rust
pub fn get_crd(svc: &str, ns: &str) -> Result<String> {
    let getargs = vec![
        "get".into(),
        format!("-n={}", ns),
        "shipcatmanifest".into(),
        "-oyaml".into(),
        svc.into(),
    ];
    kout(getargs)
}
pub fn file_vs_crd(svc: &str, conf: &Config, region: &Region) -> Result<()> {
    // local state
    let aftermf = shipcat_filebacked::load_manifest(svc, conf, region)?;
    let aftercrd = Crd::from(aftermf);
    let after = serde_yaml::to_string(&aftercrd)?;

    // crd state from kube
    let before = kube::get_crd(svc, &region.namespace)?;

    print_difference(&before, &after)
}
```

This compares generated crd (which we apply straight) with get crd -oyaml from kube.
Turns out to be useless due to the extra annotations returned, whitespace returned differently.

Tried also deserializing the crd first, but due to how deserialization is different depending on what backend we have it ends up being incompatible (evars have different serialization format internally than on disk - which is a bit unfortunate).

**Comment by clux** [comment]
will be in shipcat 0.96.0
