### ISSUE TITLE
Regional rollouts

### ISSUE THREAD

**Issue by clux** [Babylonpartners/shipcat#85]
When doing larger changes to core or charts it would be good to have a regional rollout of the shipcat version, or the charts being used.

The charts would be pretty easy:

- define chart paths in `Region` configs: (say `{'base': 'charts/base', 'elb': 'charts/elb'}`)
- override in test regions

shipcat version would be a bit more complicated because you need to read the shipcat config before checking out the version of shipcat you need to roll things out.

We could establish a convention of putting the `shipcat` version in the `Region` struct, but that means you'd have to do a bit of an annoying `yq` on the file to figure out what version to use, and it would make it hard to change those structs at the same time without removing all the `deny_unknown_fields` annotations.

yq magic would be:

```sh
yq -y ".regions | map(select(.name == \"my-region\") .)" < ${SHIPCAT_MANIFEST_DIR}/shipcat.conf | yq '.version'
```

Which makes the unknown fields question the key one. We should probably change it to a `warn` to better deal with breaking changes for raftcat anyway.

Better suggestions welcome, but this probably solves it:

- [ ] put shipcat version to use per region in `Region` struct
- [ ] ci should use `yq` to decide shipcat version for reconciliation
- [ ] `s/deny/warn` in unknown_fields if possible for better backwards/forwards compat

**Comment by JoseAlban** [comment]
Hmm - that's a good feat to have - but thinking of maybe having a global version and region-overrides, so shipcat itself can exec again into appropriate version if there's an override - this way, if eg v0.84.0 knows the region-override field, we don't need to deal with yq or unknown_fields compat (maybe?).

**Comment by janslow** [comment]
Rather than rolling out per region, can we just restrict it to per environment. i.e., you can set `dev: 0.82.0` and `staging: 0.81.0` etc.

This will help to limit the complexity of manifests, especially as the number of regions grows.

**Comment by clux** [comment]
We're experimenting with this now. A key subtlety:

client side validation in manifests repo needs to be parametrised per region/environment. otherwise we'll get reconciles failing for older versions when manifests were validated for a newer version.

@JoseAlban is having a go at it today.

**Comment by clux** [comment]
More thoughts on this. A simplifying start is to just replace `version` with `versions` in the config:

```yaml
versions:
  dev: 0.88.0
  staging: 0.87.0
  preprod: 0.87.0
  prod: 0.87.0
```

so that:
- reconcile jobs can grab it from `yq ".versions.dev" -r < shipcat.conf`
- `shipcat` internal version check can check against the highest found in file (using lax yaml parsing)
- operators (`raftcat`) track that number in the relevant clusters

the **validation is the hard part**, and there are some trade-offs (see follow up post).

**Comment by clux** [comment]
validation options:
## 1. Validate everything simultaneously with all versions
Suppose we have an extra workflow task that just runs validate on all the non-prod versions (if there's more than one in `versions`). That way it's not too much duplication, and it's only there when a rollout is actually in progress.

#### CON: breaking manifest/config cannot be gradually rolled out
because validation now happens on more than one version of shipcat, all manifests/the config must validate against both versions simultaneously.

thus breaking  syntax changes herein would have to be designed as a separate release that's reworked in manifests simultaneously and **NOT** gradually rolled out. it's completely doable:

- **Added syntax**: introduced easily without the need for graduals.
- **Removed syntax**: removed with manifests along with bump, removed everywhere
- **Renamed syntax**: add syntax, then remove syntax over two releases

requires that shipcat devs keep this in their heads as they are changing it, but it can be documented..

#### PRO: easy circle addition
even if [circleci does not let you specify dynamic image tags in .circleci/config.yml](https://discuss.circleci.com/t/specify-docker-tag-via-environment-variable/17265), it's still easy to run with remote docker and dynamically figure out the image to use.

## 2. Validate per environment
Suppose ALL validation jobs are wrapped in jobs that pick the correct shipcat image via remote docker depending on the environment they want to validate. This will allow gradual rollouts of breaking syntax changes (even if you'd have to put the new syntax in sub-manifests only)

#### PRO: breaking changes of manifests can be gradually rolled out
people can put new syntax in `dev-uk.yml` and then, once verified, they can moved it into `shipcat.yml` (or indeed, to other `<env>.yml` files). it's awkward, but it's one step up.

#### CON: breaking changes of config format can't be rolled out
because it's all just one file, we would have to split the file first per region so that it can be parsed by the right shipcat at the right time.

the config **CAN** be split however, but it's also a bit of work.
you would get into the same issue of region split vs. environment split at that point as well...

#### CON: remote docker slowdown
you now need to run in multiple execution contexts, one to decide what image to pull, then one to run in that context. ideally circle is fast, but usually most of the time is spent in circleci's provisioning of nodes so who knows..

#### CON: multiple docker invocations slowdown
you'll now fetch potentially multiple images in each verify job, it's inevitable that it will slow down verifications.

#### CON: splitting jobs over into multiple images is a bit of work
there's like 7 validation jobs atm, and they all rely on a fixed version, they shell out to shipcat at various points perhaps to cross-reference with other regions. i'm not even sure this is feasible to do.

## 3. validate per environment + split config
Same as 2. but also split the config so that we can roll out breaking changes of the config and manifests simultaneously. Thought experiment:

#### CON: still can't guarantee that misc. scripts don't break in response to breaking changes
things shell out, sometimes you gotta deal with it...
#### CON: still can't gradually rollout stuff in the global config
whatever the global config is, `clusters`, `teams`, `versions`.

## closing note
ultimately you gotta draw the line somewhere. my preference is 1, but curious to see what people think.

**Comment by JoseAlban** [comment]
Had a read on above and it looks like `1` is the most likely to have less friction indeed - still not ideal as there might be unnecessary work done, ie dev wants shipcat X and prod Y, but dev gets validated against X and Y versions of shipcat.

But yes as described above for those cases we do the manifest change on all + bump all which is equivalent for what we have today - just a bit more verbose. So `1` is only allowing the gradual rollout on addition which is great.

| but it can be documented..

definitely ^ :D

**Comment by clux** [comment]
1. is done.

Switching over jobs to use `export SHIPCAT_VER="$(yq ".versions.dev" -r < shipcat.conf)"` to use correct version now.

**Comment by clux** [comment]
Opening a more specific one for handling charts better.
