### ISSUE TITLE
CLI option to set Kubectl context

### ISSUE THREAD

**Issue by janslow** [Babylonpartners/shipcat#91]
Currently Shipcat executes `kubectl config current-context` to discover the current context, which it uses to choose the region.

It would be useful if there was a way to override this, e.g., a `--context` option (which matches the `kubectl` option) or `--region`.

**Comment by clux** [comment]
It uses `current-context` if there's no other information to help it decide.

`-r prod-uk` (say) is generally supported in most commands to override the region (which maps to a context) to use.

**Comment by janslow** [comment]
Ok, it's missing from `shipcat helm` commands. Could it be changed to a global option (like `--debug`)?
