### ISSUE TITLE
kong oauth client ids must be unique across a region

### ISSUE THREAD

**Issue by clux** [Babylonpartners/shipcat#97]
Otherwise you run into kongfig reconciliation errors:

```
15:51:18  Error: Conflict
15:51:18 {"client_id":"already exists with value 'SOMECLIENTID'"}
15:51:18 
```

validate this in region.rs under Kong::verify.

**Comment by janslow** [comment]
Kong consumer's client IDs will be disappearing entirely in the next few weeks, so I'd recommend against putting any effort in to fixing this.

**Comment by clux** [comment]
closing - these structs will be removed entirely.
